name: poetry

on: push

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Poetry
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create 'true'
          poetry config virtualenvs.in-project 'true'
      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/pyproject.toml') }}
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install -n --no-root
      - name: Install
        run: poetry install -n
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m unittest
